### ISSUE TITLE
CLI returns error: module 'clip' has no attribute 'load'

### ISSUE THREAD

**Issue by Ariloum** [vladmandic/sd-extension-aesthetic-scorer#12]
Hello, I'm trying to get the score by command line on the windows system but keep getting the error.
Did I miss something?

python --version
Python 3.10.6

python aesthetic-scorer-cli.py "C:\stable-diffusion\stable-diffusion-webui-2023-09\extensions\sd-extension-aesthetic-scorer\tst.png"
Loading CLiP model: ViT-L/14
Traceback (most recent call last):
  File "c:\stable-diffusion\stable-diffusion-webui-2023-09\extensions\sd-extension-aesthetic-scorer\aesthetic-scorer-cli.py", line 141, in <module>
    aesthetic_score(fn, params)
  File "c:\stable-diffusion\stable-diffusion-webui-2023-09\extensions\sd-extension-aesthetic-scorer\aesthetic-scorer-cli.py", line 84, in aesthetic_score
    load_models(params)
  File "c:\stable-diffusion\stable-diffusion-webui-2023-09\extensions\sd-extension-aesthetic-scorer\aesthetic-scorer-cli.py", line 62, in load_models
    clip_model, _clip_preprocess = clip.load(params.clip, jit = False, device = device)
AttributeError: module 'clip' has no attribute 'load'

**Comment by vladmandic** [comment]
you have the wrong clip package.
```shell
pip uninstall clip
pip install <git+https://github.com/openai/CLIP.git>
```

**Comment by Ariloum** [comment]
thanks, another clip solved the issue
