### ISSUE TITLE
ModuleNotFoundError: No module named 'pythoncom'

### ISSUE THREAD

**Issue by axemaster** [vladmandic/sd-extension-aesthetic-scorer#3]
I get this every time I start A1111. On a Mac M1. This looks like a windows-only package. Do you need it?

ERROR:root:Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
Traceback (most recent call last):
  File "/Users/macuser/work/A1111/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py", line 26, in <module>
    from tools.add_tags import tag_files
  File "/Users/macuser/work/A1111/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/tools/add_tags.py", line 6, in <module>
    import pythoncom
ModuleNotFoundError: No module named 'pythoncom'
Loading weights [dc027dbbf9] from /Users/macuser/work/A1111/stable-diffusion-webui/models/Stable-diffusion/nsfw/clarity_14.safetensors

**Comment by vladmandic** [comment]
Ahhh, but that's the whole point - you get the error not from my extension but from the other one which is windows-only!

So, uninstall that one and install this one. 😁

**Comment by axemaster** [comment]
Got it, thanks

**Comment by axemaster** [comment]
Please close issue, apparently I can't.
