### ISSUE TITLE
Error grabbing exif data when using cli version

### ISSUE THREAD

**Issue by briancw** [vladmandic/sd-extension-aesthetic-scorer#7]
Running the cli version on a generated image returned:
```
Traceback (most recent call last):
  File "/mnt/sd/stable-diffusion-webui/extensions/sd-extension-aesthetic-scorer/aesthetic-scorer-cli.py", line 119, in <module>
    aesthetic_score(fn, params)
  File "/mnt/sd/stable-diffusion-webui/extensions/sd-extension-aesthetic-scorer/aesthetic-scorer-cli.py", line 84, in aesthetic_score
    exif = Exif(img)
  File "/mnt/sd/stable-diffusion-webui/extensions/sd-extension-aesthetic-scorer/exif.py", line 20, in __init__
    self.load(image)
  File "/mnt/sd/stable-diffusion-webui/extensions/sd-extension-aesthetic-scorer/exif.py", line 29, in load
    exif_dict=dict(img._getexif().items())
AttributeError: 'NoneType' object has no attribute 'items'
```

This was on a linux based install using generated png images.

**Comment by briancw** [comment]
Seems to work fine on JPGs but not PNGs, which I guess makes sense, since A1111 uses a different method for saving generating data on PNG's than it does JPG's.

**Comment by vladmandic** [comment]
thats all true, but if i chose to support jpg, i should also support other image formats.
i've just updated extension, tested with jpeg, png and webp - all should work now.
